### ISSUE TITLE
Doesn't Work on October 3

### ISSUE THREAD

**Issue by triasrahman** [mplodowski/backupmanager-plugin-public#29]
**Describe the bug**
The latest version is not compatible to October 3.

**To Reproduce**
1. Run the database backup
2. See error
```
TypeError: Symfony\Component\Process\Process::__construct(): Argument #1 ($command) must be of type array, string given, called in /var/www/html/plugins/renatio/backupmanager/vendor/spatie/db-dumper/src/Databases/MySql.php on line 140 and defined in /var/www/html/vendor/symfony/process/Process.php:143
Stack trace:
#0 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/db-dumper/src/Databases/MySql.php(140): Symfony\Component\Process\Process->__construct(''mysqldump' --d...')
#1 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(246): Spatie\DbDumper\Databases\MySql->dumpToFile('/var/www/html/s...')
#2 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map(Object(Closure), Array, Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(723): Illuminate\Support\Arr::map(Array, Object(Closure))
#5 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(249): Illuminate\Support\Collection->map(Object(Closure))
#6 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(166): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(142): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(998): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
```

**Expected behavior**
The backup should be done properly.

**October version**
3.0.43

**Plugin version**
3.3.4

**Additional context**
I can't install the latest version because `composer.json` requires October 2.

**Comment by triasrahman** [comment]
Thank you @mplodowski . It works on the latest version.

**Comment by KensingtonWebmaster** [comment]
Hi, I have some error. I just upgraded my client's October CMS Project from v1.0 to v3.5. and the version of the backup_Manager is v3.3.4. When I click on the "check for update" button on the admin dashboard, they are not updating my software automatically. Could you please tell me that how to upgrade the plugin to the latest version?

**Comment by mplodowski** [comment]
Hi @KensingtonWebmaster,

October from version 2 is using composer to manage dependencies.

You must add/modify composer.json file to use the latest version of my plugin like so:

`"renatio/backupmanager-plugin": "^5.1"`

Then run `composer update`.

After update run `php artisan october:migrate`.

I hope this helps.
